cookie:
  expiry_days: 30
  key: brain_aneurysm
  name: brain_aneurysm_cookie
credentials:
  usernames:
    admin1:
      email: admin1@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin 1
      password: $2b$12$CAG5Zpaoz1nu7fTWCoWe6efIAyT1yomB490GtIz4/XRToFwBxEkNe
    admin2:
      email: admin2@yahoo.com
      logged_in: false
      name: Admin
      password: $2b$12$o5AAc2vmhPJj37AnGmXAhewCMRMPEkgDwdmzshK8/VC9SUSCG9eIW
    guest:
      email: guest@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Guest
      password: $2b$12$VtZrReGxPBUF8LGwmJA1deUp3xJLFSpsSzHtwU9gQEt6yMe8P6CnK
    kokonen:
      email: kokonen6969@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Kokonen
      password: $2b$12$53TkNKhvvF5k5CqEQ6GPN.YVilN3BqCa5Bk2Q.zQdTgzOza0uhXCS
    taylor:
      email: ts000@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Taylor
      password: $2b$12$x.MR4VDKeIw58h9A4ox6VOm43COUqtZ5y7jObx.nbiOA4bvlsVI8q
pre-authorized:
  emails:
  - test001@gmail.com
