cookie:
  expiry_days: 0
  key: brain_aneurysm
  name: brain_aneurysm_cookie
credentials:
  usernames:
    admin1:
      email: admin1@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin 1
      password: $2b$12$CAG5Zpaoz1nu7fTWCoWe6efIAyT1yomB490GtIz4/XRToFwBxEkNe
    admin2:
      email: admin2@yahoo.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin
      password: $2b$12$o5AAc2vmhPJj37AnGmXAhewCMRMPEkgDwdmzshK8/VC9SUSCG9eIW
    admin3:
      email: admin3@gmail.student.edu
      failed_login_attempts: 0
      logged_in: false
      name: Admin Three
      password: $2b$12$/Jgba8Tva3GtYleygd4FN.ziL.LR/fVMBZWKA74WfwNXeqUsWZaIu
    admin4:
      email: admin4@gmail.student.edu
      failed_login_attempts: 0
      logged_in: false
      name: Admin Four
      password: $2b$12$Tz3L0hYp6fBlsWHxZrtjWuQs3ncZ05dBcfnv6RQiWLX.D7.9hKGai
    admin5:
      email: admin5@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin Five
      password: $2b$12$/sqv8e9YOj9s/GX9UTf1v.Yeuulj3AYrL8nJ159q/r9bE/QdU9.i.
    guest:
      email: guest@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Guest
      password: $2b$12$VtZrReGxPBUF8LGwmJA1deUp3xJLFSpsSzHtwU9gQEt6yMe8P6CnK
    kokonen:
      email: kokonen6969@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Kokonen
      password: $2b$12$53TkNKhvvF5k5CqEQ6GPN.YVilN3BqCa5Bk2Q.zQdTgzOza0uhXCS
    steve:
      email: appleinc123@ceo.apple.com
      failed_login_attempts: 0
      logged_in: false
      name: Apple CEO Steve Jobs
      password: $2b$12$ZFBr.x6/I1dlUzA948uTAe6D4.QClJpkuKwdepfYwSdM4wLY17Sw.
    student:
      email: student001@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Student
      password: $2b$12$K1fQ5.Yf4c9NpFqOn9sHouGv17c79PkchfrKpA4nA/2m/8GHVWUsW
    taylor:
      email: ts000@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Taylor
      password: $2b$12$x.MR4VDKeIw58h9A4ox6VOm43COUqtZ5y7jObx.nbiOA4bvlsVI8q
pre-authorized:
  emails:
  - test001@gmail.com
