name: env_name
channels:
  - simpleitk
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - joblib=0.17
  - nibabel=3.2
  - simpleitk=2.0
  - pandas=1.2
  - scipy=1.6
  - pip:
    - numpy==1.23.5
    - connected-components-3d==3.12.4
    - scikit-image==0.18
    - opencv-python==4.9.0.80
    - antspyx==0.4.2
    - tensorflow==2.15
    - matplotlib==3.2
